include:
  - docker/backend/compose.backend.yml
  - docker/frontend/compose.frontend.yml
  - docker/caddy/compose.caddy.yml

services:
  # Base de datos MySQL
  db:
    image: mysql:8.0
    container_name: logisteia_db
    restart: always
    environment:
      MYSQL_DATABASE: Logisteia
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql
      - ./src/sql/bbdd.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - logisteia_network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: logisteia_pma
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    depends_on:
      - db
    networks:
      - logisteia_network

volumes:
  db_data:
  caddy_data:
  caddy_config:

networks:
  logisteia_network:
    driver: bridge