# Docker Compose para el Frontend Angular
services:
  frontend:
    build:
      context: ../..
      dockerfile: Dockerfile
    container_name: logisteia_frontend
    restart: always
    depends_on:
      - backend
    networks:
      - logisteia_network
