# Docker Compose para Caddy (Proxy y servidor web)
services:
  web:
    image: caddy:alpine
    container_name: logisteia_web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ../../src/www:/var/www/html
    depends_on:
      - backend
      - frontend
    networks:
      - logisteia_network
