services:
  # Frontend Angular + Caddy
  web:
    build:
      context: ../..
      dockerfile: docker/frontend/Dockerfile
    container_name: logisteia_web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - logisteia_network

networks:
  logisteia_network:
    external: true
    name: docker_logisteia_network