services:
  # Base de datos MySQL
  db:
    image: mysql:8.0
    container_name: logisteia_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    environment:
      MYSQL_DATABASE: Logisteia
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db_data:/var/lib/mysql
      - ../src/sql/bbdd.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      logisteia_network:
          ipv4_address: 10.0.0.2

  # Backend PHP con Apache
  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    container_name: logisteia_backend
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: Logisteia
      DB_USER: root
      DB_PASS: ${DB_PASS}
    networks:
      logisteia_network:
          ipv4_address: 10.0.0.4

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: logisteia_pma
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    depends_on:
      - db
    networks:
      logisteia_network:
          ipv4_address: 10.0.0.3

  # Frontend Angular + Caddy
  web:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    container_name: logisteia_web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - logisteia_network

volumes:
  db_data:

networks:
  logisteia_network:
    external: true
    name: docker_logisteia_network